apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: staging
type: Opaque
stringData:
  DB_HOST:     "postgres-service.production.svc.cluster.local"
  DB_PORT:     "5432"
  DB_NAME:     "itemsdb"
  DB_USER:     "apiuser"
  DB_PASSWORD: "Ch4ng3M3inPr0d!"
