apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: production
type: Opaque
stringData:
  DB_HOST:     "postgres-service"
  DB_PORT:     "5432"
  DB_NAME:     "itemsdb"
  DB_USER:     "apiuser"
  DB_PASSWORD: "Ch4ng3M3inPr0d!"
